/**
 ******************************************************************************
 * @file    vl53l9_device.c
 * @author  IMD Software Team
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "vl53l9_device.h"
#include "main.h"

extern I3C_HandleTypeDef hi3c1;

vl53l9_device_t device[NB_DEVICES] = {
#ifdef CONFIG_HW_STEVAL_MIPI
    { .bus = &hi3c1,
      .bus_type = PLATFORM_BUS_I3C | PLATFORM_BUS_CSI,
      .address = VL53L9_DEFAULT_ADDRESS,
      .vdda = VDDA_2V8,
      .vddio = VDDIO_1V8,
      .ext_clock = 12.5e6, // NOTE: clock generated by the host
      .intr = { .pin = TOF_INT_Pin, .port = TOF_INT_GPIO_Port },
      .xshut = { .pin = NRST_CAM_Pin, .port = NRST_CAM_GPIO_Port } },
#endif
#ifdef CONFIG_HW_X_NUCLEO
    { .bus = &hi3c1,
      .bus_type = PLATFORM_BUS_I3C,
      .address = VL53L9_DEFAULT_ADDRESS,
      .vdda = VDDA_2V8,
      .vddio = VDDIO_1V8,
      .ext_clock = 12.0e6, // NOTE: uncomment this when SW1 set to INT
      // .ext_clock = 12.5e6, // NOTE: uncomment this when SW1 set to EXT
      .intr = { .pin = INTR_ARD_Pin, .port = INTR_ARD_GPIO_Port },
      .xshut = { .pin = XSHUT_ARD_Pin, .port = XSHUT_ARD_GPIO_Port } },
#endif
};
